[package]
name = "s3-server"
version = "0.2.0"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/datenlord/s3-server"
readme = "README.md"
description = "An experimental generic S3 server"
keywords = ["s3"]
categories = ["web-programming", "web-programming::http-server"]

[features]
default = []
binary = [
    "dotenv", 
    "structopt", 
    "structopt-flags",
    "tracing-subscriber"
]

[[bin]]
name = "s3-server"
required-features = ["binary"]

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"]}
async-trait = "0.1.53"
backtrace = "0.3.65"
base64-simd = "0.8.0"
chrono = "0.4.19"
const-str = { version = "0.3.1", features = ["verify-regex"] }
dotenv = { version = "0.15.0", optional = true }
futures = "0.3.21"
hex-simd = "0.8.0"
hmac = "0.12.1"
http = "0.2.7"
httparse = "1.7.0"
hyper = { git = "https://github.com/wasix-org/hyper.git", branch = "v0.14.28", features = ["stream", "http1", "http2", "tcp", "server"] }
md-5 = "0.10.1"
memchr = "2.4.1"
mime = "0.3.16"
nom = "7.1.1"
once_cell = "1.10.0"
path-absolutize = { version = "3.1.1", features = [ "use_unix_paths_on_wasm" ] }
pin-project-lite = "0.2.8"
quick-xml = { version = "0.36.1", features = ["serialize"] }
regex = "1.5.5"
rusoto_core = { git = "https://github.com/wasix-org/rusoto.git", branch = "v0.48.0", version = "=0.48.0" }
rusoto_s3 = { git = "https://github.com/wasix-org/rusoto.git", branch = "v0.48.0", version = "=0.48.0" }
serde = "1.0.136"
serde_json = "1.0.79"
serde_urlencoded = "0.7.1"
sha2 = "0.10.2"
smallvec = "1.8.0"
structopt = { version = "0.3.26", optional = true }
structopt-flags = { version = "0.3.6", optional = true }
thiserror = "1.0.30"
tokio = { git = "https://github.com/wasix-org/tokio.git", branch = "wasix-1.35.1", default-features = false, features = ["rt-multi-thread", "macros", "fs", "io-util", "signal"] }
tracing = "0.1.34"
tracing-error = "0.2.0"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", optional = true, features = ["env-filter", "time"] }
transform-stream = "0.3.0"
urlencoding = "2.1.0"
uuid = { version = "1.0.0", features = ["v4"] }
xml-rs = "0.8.4"
libc = { version = "=0.2.152", git = "https://github.com/wasix-org/libc", branch = "v0.2.152"}

[dev-dependencies]
anyhow = { version = "1.0.57" }
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "time"] }

[profile.dev]
codegen-units = 1
debug = false
debug-assertions = false
opt-level = 3
panic = "abort"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = "fat"
opt-level = 3
panic = "abort"
rpath = false
strip = true

[patch.crates-io]
libc = { git = "https://github.com/wasix-org/libc.git", branch = "v0.2.152" }
