[package]
name = "wasmer/s3-server"
version = "0.1.14"
description = "S3 server using durable instances."
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/wasix-org/s3-server"

[fs]
"/fe" = "./src/fe"
"/s3" = "./s3"

[[module]]
name = "s3-server"
source = "./target/wasm32-wasmer-wasi/release/s3-server.wasm"

[[command]]
name = "s3-server"
module = "s3-server"
runner = "wasi"
